tactician:
    default_bus: commandbus
    commandbus:
        commandbus:
            middleware:
                - tactician.middleware.validator
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler
