# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Todora\Todos\Infrastructure\Symfony\UserProvider\User:
            algorithm: auto

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        dbal:
            id: Todora\Todos\Infrastructure\Symfony\UserProvider\DbalUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false

        board:
            anonymous: ~
            provider: dbal
            form_login:
                login_path: todora.login
                check_path: todora.login
                always_use_default_target_path: true
                default_target_path: todora.board
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: todora.logout
                target: todora.home

    access_control:
        - { path: ^/board, roles: ROLE_USER }
