sensio_framework_extra:
    router:      { annotations: false }
    request:     { converters: false, auto_convert: false }
    view:        { annotations: false }
    cache:       { annotations: false }
    security:    { annotations: false }
    psr_message: { enabled: true }
