snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: "%kernel.debug%"
    session:
        client: default
        ttl: 3600
