language: php

sudo: false

dist: bionic

addons:
    postgresql: "9.6"

services:
    - postgresql

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.3'

matrix:
    fast_finish: true

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"
        - DATABASE_URL="pgsql://todora_test:todora_test@127.0.0.1:5432/todora_test?charset=UTF-8&serverVersion=9.6"

before_script:
    - psql -c "CREATE DATABASE todora_test;" -U postgres
    - psql -c "CREATE USER todora_test WITH PASSWORD 'todora_test';" -U postgres

before_install:
    - source .travis/xdebug.sh
    - xdebug-disable
    - yes '' | pecl install -f apcu-5.1.17
    - composer self-update

install:
    - travis_retry composer install -a $DEFAULT_COMPOSER_FLAGS
    - travis_retry composer bin all install -a $DEFAULT_COMPOSER_FLAGS

script:
    # this step is needed by syfmony-plugin for phpstan
    - php bin/console cache:warmup -e test
    - composer todora:migrate:local
    - composer todora:analyze
    - vendor/bin/phpunit

notifications:
    email: false
