language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.2'

matrix:
    fast_finish: true

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"

before_install:
    - composer self-update

install:
    - travis_retry composer install -a $DEFAULT_COMPOSER_FLAGS
    - travis_retry composer bin all install -a $DEFAULT_COMPOSER_FLAGS

script:
    - vendor/bin/php-cs-fixer fix -v --diff --dry-run
    - vendor/bin/phpunit

notifications:
    email: false
