language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.2'

matrix:
    fast_finish: true

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"

before_install:
    - source .travis/xdebug.sh
    - xdebug-disable
    - yes '' | pecl install -f apcu-5.1.9
    - composer self-update

install:
    - travis_retry composer install -a $DEFAULT_COMPOSER_FLAGS
    - travis_retry composer bin all install -a $DEFAULT_COMPOSER_FLAGS

script:
    - composer todora:analyze
    - vendor/bin/phpunit

notifications:
    email: false
