imports:
    - { resource: "services/application/command_handler.yml" }
    - { resource: "services/aliases.yaml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Todora\Application\:
        resource: "%kernel.project_dir%/src/Application"
        exclude: "%kernel.project_dir%/src/Application/{Command,Query}"

    Todora\Infrastructure\:
        resource: "%kernel.project_dir%/src/Infrastructure"

    Todora\UserInterface\:
        resource: "%kernel.project_dir%/src/UserInterface"
        public: true

    Todora\Application\EventListener\InvalidCommandExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
