todora.home:
    controller: Todora\Todos\UserInterface\HomeAction
    methods: GET
    path: /

todora.login:
    controller: Todora\Todos\UserInterface\SignInAction
    methods: [GET, POST]
    path: /login

todora.logout:
    methods: GET
    path: /logout

todora.board:
    controller: Todora\Todos\UserInterface\BoardAction
    methods: GET
    path: /board
