# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Todora\:
        resource: '../src/*'
        exclude: '../src/*/UserInterface'

    Todora\Todos\UserInterface\:
        resource: '../src/Todos/UserInterface/*'
        public: true

    Todora\Todos\Application\Command\:
        resource: '../src/Todos/Application/Command/*Handler.php'
        tags:
            - { name: tactician.handler, typehints: true, bus: commandbus }

    Todora\SharedKernel\Infrastructure\CommandBus\TacticianCommandBus:
        arguments:
            $commandBus: '@tactician.commandbus.commandbus'

    Symfony\Component\Security\Core\Encoder\Argon2iPasswordEncoder: ~

    Todora\SharedKernel\Application\CommandBusInterface:
        alias: Todora\SharedKernel\Infrastructure\CommandBus\TacticianCommandBus
