# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Todora\Todos\:
        resource: '../src/Todos/*'
        exclude: '../src/Todos/{UserInterface,Application/Command,Application/Query}'

    Todora\Todos\UserInterface\:
        resource: '../src/Todos/UserInterface'
        public: true

    Todora\Todos\Application\Command\:
        resource: '../src/Todos/Application/Command/*Handler.php'
        tags:
            - { name: tactician.handler, typehints: true, bus: commandbus }

    Todora\Todos\Application\Query\UniqueUsernameQueryInterface:
        alias: Todora\Todos\Infrastructure\Doctrine\DbalUniqueUsernameQuery
